import { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    absolute: "Complex Dashbord",
  },
  description: "Generated by create next app",
};
const ComplexDashboard = async () => {
  return <>Complex Dashboard</>;
};

export default ComplexDashboard;
