// "use client";
// import { use } from "react";
import { Metadata } from "next";
import { use } from "react";

export const metadata: Metadata = {
  title: {
    absolute: "Articles Details",
  },
  description: "Generated by create next app",
};
const Articles = ({
  params,
  searchParams,
}: {
  params: Promise<{ articleId: string }>;
  searchParams: Promise<{ lang?: "en" | "fr" }>;
}) => {
  const { articleId } = use(params);
  const { lang } = use(searchParams);

  return (
    <>
      Articles {articleId} reading in {lang}
    </>
  );
};

export default Articles;
