import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "./components/header/header";
import { ThemeProvider } from "./components/theme-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    default: "Next Tutorial",
    template: "%s | Gal",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <ThemeProvider>
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            style={{
              display: "flex",
              flexDirection: "column",
              minHeight: "100vh", // full height of viewport
            }}
          >
            <Header />
            <main style={{ flex: 1 }}>{children}</main>
            <footer style={{ backgroundColor: "lightblue", padding: "1rem" }}>
              Footer
            </footer>
          </body>
        </ThemeProvider>
      </html>
    </ClerkProvider>
  );
}
