import { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: {
    absolute: "Articles",
  },
  description: "Generated by create next app",
};
const Articles = () => {
  return (
    <>
      Articles
      <h3>
        <Link href={"/articles/123?lang=en"}>Article 123</Link>
      </h3>
      <h3>
        <Link href={"/articles/124?lang=en"}>Article 124</Link>
      </h3>
      <h3>
        <Link href={"/articles/125?lang=en"}>Article 125</Link>
      </h3>
    </>
  );
};

export default Articles;
