import { Metadata } from "next";

export const metadata: Metadata = {
  //   title: "Blog",
  title: {
    absolute: "Blog",
  },
  description: "Generated by create next app",
};
const Blog = async () => {
  await new Promise((resolve) => {
    setTimeout(() => {
      resolve("Resolved");
    }, 200);
  });
  return <>Blog</>;
};

export default Blog;
